create database customer_behavior_analysis ;
use customer_behavior_analysis ;
select * from customer ;
-- PROBLEM STATEMENTS
-- --Q1. What is the total revenue generated by male vs. female customers?
select gender ,
sum(purchase_amount)as total_revenue from customer
group by 1 ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id , purchase_amount
from customer
where discount_applied  = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer );

-- we can solve the above problem statements by cte and window function
with cte as ( select customer_id ,
discount_applied, purchase_amount,
 avg(purchase_amount) over() as avg_all from customer)
select customer_id , purchase_amount ,
avg_all from cte where discount_applied = 'Yes' and purchase_amount >= avg_all ;

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased , round(avg(review_rating),2) as avg_review_rating
from customer 
group by 1  order by 1,2 desc limit 5 ; 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select distinct(shipping_type) from customer ;
select shipping_type , avg(purchase_amount) as avg_purch_amnt
from customer
where shipping_type in('standard' , 'EXPRESS')
group by 1 ;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select   subscription_status,
count(customer_id) as total_customer,
 avg(purchase_amount) as avg_spend,
 sum(purchase_amount) as total_revenue from customer
 group by 1 ;

-- Q6. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q7. What are the top 3 most purchased products within each category? 
select * from customer limit 2;
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--  Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
